### status
GET http://localhost:4444/v1/status
Content-Type: application/json


### create
POST http://localhost:4444/v1/register
Content-Type: application/json

{
  "email": "javlonrahimov1212@gmail.com",
  "password": "pa55word12",
  "name": "Javlon"
}


### verify
POST http://localhost:4444/v1/verify
Content-Type: application/json

{
  "email": "javlonrahimov1212@gmail.com",
  "otp": "3704"
}

### login
POST http://localhost:4444/v1/login
Content-Type: application/json

{
  "email": "javlonrahimov1212@gmail.com",
  "password": "pa55word12"
}

### Get user quotes
GET https://localhost:4444/quote/69359037-9599-48e7-b8f2-48393c019135?page_size=30

### Get quote states
GET http://localhost:4444/v1/quote/states
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo0NDQ0Iiwic3ViIjoiNTQ3NDkwZDQtNzNjOS00ODU1LWJhNDItOThkYTA5MTA1NDgwIiwiYXVkIjpbImh0dHBzOi8vbG9jYWxob3N0OjQ0NDQiXSwiZXhwIjoxNjcxMzY2ODE5Ljg3OTY2NjgsIm5iZiI6MTY3MDc2MjAxOS44Nzk2ODQ0LCJpYXQiOjE2NzA3NjIwMTkuODc5NjgzNX0.aMcPS-hTJMABlvnj0uFUn9TpZ3Efznv3wcSjcbFaSdc

### Create Quote
POST http://localhost:4444/v1/quote
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo0NDQ0Iiwic3ViIjoiNTQ3NDkwZDQtNzNjOS00ODU1LWJhNDItOThkYTA5MTA1NDgwIiwiYXVkIjpbImh0dHBzOi8vbG9jYWxob3N0OjQ0NDQiXSwiZXhwIjoxNjcxMzY2ODE5Ljg3OTY2NjgsIm5iZiI6MTY3MDc2MjAxOS44Nzk2ODQ0LCJpYXQiOjE2NzA3NjIwMTkuODc5NjgzNX0.aMcPS-hTJMABlvnj0uFUn9TpZ3Efznv3wcSjcbFaSdc

{
  "author": "test",
  "text": "This is a sample quote",
  "hashtagIDs": [
    "5aa15f1f-12d8-4924-80e8-267fefceca97"
  ],
  "photoID": "ef8abf87-2e2e-45e8-8bd2-22e2330e225b",
  "stateID": "8847de4f-73f3-4d47-902b-a9c162104533"
}

### get quotes
GET http://localhost:4444/v1/quotes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo0NDQ0Iiwic3ViIjoiNTQ3NDkwZDQtNzNjOS00ODU1LWJhNDItOThkYTA5MTA1NDgwIiwiYXVkIjpbImh0dHBzOi8vbG9jYWxob3N0OjQ0NDQiXSwiZXhwIjoxNjcxMzY2ODE5Ljg3OTY2NjgsIm5iZiI6MTY3MDc2MjAxOS44Nzk2ODQ0LCJpYXQiOjE2NzA3NjIwMTkuODc5NjgzNX0.aMcPS-hTJMABlvnj0uFUn9TpZ3Efznv3wcSjcbFaSdc

### create hashtag
POST http://localhost:4444/v1/hashtag
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo0NDQ0Iiwic3ViIjoiNTQ3NDkwZDQtNzNjOS00ODU1LWJhNDItOThkYTA5MTA1NDgwIiwiYXVkIjpbImh0dHBzOi8vbG9jYWxob3N0OjQ0NDQiXSwiZXhwIjoxNjcxMzY2ODE5Ljg3OTY2NjgsIm5iZiI6MTY3MDc2MjAxOS44Nzk2ODQ0LCJpYXQiOjE2NzA3NjIwMTkuODc5NjgzNX0.aMcPS-hTJMABlvnj0uFUn9TpZ3Efznv3wcSjcbFaSdc

{
  "value": "motivation"
}

### get hashtags
GET http://localhost:4444/v1/hashtags?page=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo0NDQ0Iiwic3ViIjoiNTQ3NDkwZDQtNzNjOS00ODU1LWJhNDItOThkYTA5MTA1NDgwIiwiYXVkIjpbImh0dHBzOi8vbG9jYWxob3N0OjQ0NDQiXSwiZXhwIjoxNjcxMzY2ODE5Ljg3OTY2NjgsIm5iZiI6MTY3MDc2MjAxOS44Nzk2ODQ0LCJpYXQiOjE2NzA3NjIwMTkuODc5NjgzNX0.aMcPS-hTJMABlvnj0uFUn9TpZ3Efznv3wcSjcbFaSdc

### get quote hashtags
GET http://localhost:4444/v1/hashtags/59dc414b-9674-4065-a2bd-f38342214227
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo0NDQ0Iiwic3ViIjoiNTQ3NDkwZDQtNzNjOS00ODU1LWJhNDItOThkYTA5MTA1NDgwIiwiYXVkIjpbImh0dHBzOi8vbG9jYWxob3N0OjQ0NDQiXSwiZXhwIjoxNjcxMzY2ODE5Ljg3OTY2NjgsIm5iZiI6MTY3MDc2MjAxOS44Nzk2ODQ0LCJpYXQiOjE2NzA3NjIwMTkuODc5NjgzNX0.aMcPS-hTJMABlvnj0uFUn9TpZ3Efznv3wcSjcbFaSdc

### get photos
GET http://localhost:4444/v1/photos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo0NDQ0Iiwic3ViIjoiNTQ3NDkwZDQtNzNjOS00ODU1LWJhNDItOThkYTA5MTA1NDgwIiwiYXVkIjpbImh0dHBzOi8vbG9jYWxob3N0OjQ0NDQiXSwiZXhwIjoxNjcxMzY2ODE5Ljg3OTY2NjgsIm5iZiI6MTY3MDc2MjAxOS44Nzk2ODQ0LCJpYXQiOjE2NzA3NjIwMTkuODc5NjgzNX0.aMcPS-hTJMABlvnj0uFUn9TpZ3Efznv3wcSjcbFaSdc


### get states
GET http://localhost:4444/v1/quote/states
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo0NDQ0Iiwic3ViIjoiNTQ3NDkwZDQtNzNjOS00ODU1LWJhNDItOThkYTA5MTA1NDgwIiwiYXVkIjpbImh0dHBzOi8vbG9jYWxob3N0OjQ0NDQiXSwiZXhwIjoxNjcxMzY2ODE5Ljg3OTY2NjgsIm5iZiI6MTY3MDc2MjAxOS44Nzk2ODQ0LCJpYXQiOjE2NzA3NjIwMTkuODc5NjgzNX0.aMcPS-hTJMABlvnj0uFUn9TpZ3Efznv3wcSjcbFaSdc

### create state
POST http://localhost:4444/v1/quote/state
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo0NDQ0Iiwic3ViIjoiNTQ3NDkwZDQtNzNjOS00ODU1LWJhNDItOThkYTA5MTA1NDgwIiwiYXVkIjpbImh0dHBzOi8vbG9jYWxob3N0OjQ0NDQiXSwiZXhwIjoxNjcxMzY2ODE5Ljg3OTY2NjgsIm5iZiI6MTY3MDc2MjAxOS44Nzk2ODQ0LCJpYXQiOjE2NzA3NjIwMTkuODc5NjgzNX0.aMcPS-hTJMABlvnj0uFUn9TpZ3Efznv3wcSjcbFaSdc

{
  "value": "test",
  "isDefault": true
}


### set default quote state
PATCH http://localhost:4444/v1/quote/state
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo0NDQ0Iiwic3ViIjoiNTQ3NDkwZDQtNzNjOS00ODU1LWJhNDItOThkYTA5MTA1NDgwIiwiYXVkIjpbImh0dHBzOi8vbG9jYWxob3N0OjQ0NDQiXSwiZXhwIjoxNjcxMzY2ODE5Ljg3OTY2NjgsIm5iZiI6MTY3MDc2MjAxOS44Nzk2ODQ0LCJpYXQiOjE2NzA3NjIwMTkuODc5NjgzNX0.aMcPS-hTJMABlvnj0uFUn9TpZ3Efznv3wcSjcbFaSdc

{
  "id": "fe3c084f-ab1a-4eb7-97e6-721727b4e769"
}

### delete quote state
DELETE http://localhost:4444/v1/quote/state/e0af7775-142e-4176-af88-30a8b587aafd
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo0NDQ0Iiwic3ViIjoiNTQ3NDkwZDQtNzNjOS00ODU1LWJhNDItOThkYTA5MTA1NDgwIiwiYXVkIjpbImh0dHBzOi8vbG9jYWxob3N0OjQ0NDQiXSwiZXhwIjoxNjcxMzY2ODE5Ljg3OTY2NjgsIm5iZiI6MTY3MDc2MjAxOS44Nzk2ODQ0LCJpYXQiOjE2NzA3NjIwMTkuODc5NjgzNX0.aMcPS-hTJMABlvnj0uFUn9TpZ3Efznv3wcSjcbFaSdc

### set quote state
PATCH http://localhost:4444/v1/quote/set-state
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo0NDQ0Iiwic3ViIjoiNTQ3NDkwZDQtNzNjOS00ODU1LWJhNDItOThkYTA5MTA1NDgwIiwiYXVkIjpbImh0dHBzOi8vbG9jYWxob3N0OjQ0NDQiXSwiZXhwIjoxNjcxMzY2ODE5Ljg3OTY2NjgsIm5iZiI6MTY3MDc2MjAxOS44Nzk2ODQ0LCJpYXQiOjE2NzA3NjIwMTkuODc5NjgzNX0.aMcPS-hTJMABlvnj0uFUn9TpZ3Efznv3wcSjcbFaSdc

{
  "id": "985aa03e-41f0-4356-80fa-229846b72dc4",
  "stateId": "8847de4f-73f3-4d47-902b-a9c162104533"
}
